# Generated by Django 5.2.1 on 2025-08-04 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paragraphs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragraph',
            name='user',
        ),
    ]
